# Generated by Django 5.1.6 on 2025-02-28 00:32

import django.core.validators
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=model_utils.fields.StatusField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=100, no_check_for_status=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='status_changed_at',
            field=model_utils.fields.MonitorField(default=None, monitor='status', null=True, when={'approved', 'pending', 'rejected'}),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
    ]
