# Generated by Django 5.1.6 on 2025-03-01 20:32

import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0003_alter_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=model_utils.fields.StatusField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=100, no_check_for_status=True),
        ),
    ]
