# Generated by Django 5.1.6 on 2025-03-01 20:32

import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0004_alter_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status_changed_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when={'approved', 'pending', 'rejected'}),
        ),
    ]
