# Generated by Django 5.1.6 on 2025-02-13 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('province', models.CharField(max_length=50, null=True, verbose_name='استان')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='شهر')),
                ('address', models.TextField(null=True, verbose_name='آدرس')),
                ('plaque', models.CharField(null=True, verbose_name='پلاک')),
                ('unit', models.CharField(blank=True, null=True, verbose_name='واحد')),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پستی')),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
    ]
