# Generated by Django 5.1.6 on 2025-02-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_alter_orderitem_quantity'),
        ('product_app', '0002_alter_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_variation_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variation_items',
            field=models.ManyToManyField(null=True, related_name='order_items', to='product_app.productvariationitem'),
        ),
    ]
