# Generated by Django 5.1.6 on 2025-02-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_remove_orderitem_product_variation_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_discount',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_discount',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
