# Generated by Django 5.1.6 on 2025-03-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='content',
            field=models.TextField(verbose_name='پرسش/پاسخ'),
        ),
    ]
