# Generated by Django 5.1.6 on 2025-02-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_productvariationitem_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
