# Generated by Django 5.1.6 on 2025-02-17 20:33

import django.db.models.deletion
import model_utils.fields
import payment_app.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_app', '0008_alter_order_total_discount_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('ref_id', models.CharField(default=payment_app.helpers.generate_random_payment_ref_id, max_length=6, null=True)),
                ('addon_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=100, no_check_for_status=True, null=True)),
                ('finished_at', model_utils.fields.MonitorField(default=None, monitor='status', null=True, when={'failed', 'success'})),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='order_app.order')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
