# Generated by Django 5.1.6 on 2025-02-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=3, null=True, verbose_name='ارز')),
                ('rate', models.BigIntegerField(null=True, verbose_name='نرخ')),
            ],
            options={
                'verbose_name': 'نرخ ارز',
                'verbose_name_plural': 'نرخ ارزها',
            },
        ),
    ]
