# Generated by Django 5.1.6 on 2025-02-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='currency',
            field=models.CharField(max_length=50, null=True, verbose_name='ارز'),
        ),
    ]
